import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/footer'; 

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 min-h-screen">
        <Navbar />
        <div className="container mx-auto px-4">
          {children}
        </div>
        <Footer /> 
      </body>
    </html>
  );
}

